services:
  backend:
    container_name: ncfu_staging_backend
    ports:
      - target: 8000
        host_ip: "127.0.0.1"
        published: "18000"
        protocol: tcp
        mode: ingress

  bot:
    container_name: ncfu_staging_bot
    ports:
      - target: 8001
        host_ip: "127.0.0.1"
        published: "18001"
        protocol: tcp
        mode: ingress

  miniapp:
    container_name: ncfu_staging_miniapp
    ports:
      - target: 8002
        host_ip: "127.0.0.1"
        published: "18002"
        protocol: tcp
        mode: ingress

  dashboard:
    container_name: ncfu_staging_dashboard
    ports:
      - target: 8003
        host_ip: "127.0.0.1"
        published: "18003"
        protocol: tcp
        mode: ingress

  web:
    container_name: ncfu_staging_web
    ports:
      - target: 3000
        host_ip: "127.0.0.1"
        published: "13000"
        protocol: tcp
        mode: ingress

  nginx:
    profiles: ["disabled"]

  mongo:
    container_name: ncfu_staging_mongo

  redis:
    container_name: ncfu_staging_redis

volumes:
  mongo_data:
    name: ncfu_staging_mongo_data
    external: false

networks:
  ncfu_net:
    name: ncfu_staging_network
    external: false
